<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Category', 'doctrine');

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $category_name
 * @property Doctrine_Collection $EventCategory
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getCategoryName()  Returns the current record's "category_name" value
 * @method Doctrine_Collection getEventCategory() Returns the current record's "EventCategory" collection
 * @method Category            setId()            Sets the current record's "id" value
 * @method Category            setCategoryName()  Sets the current record's "category_name" value
 * @method Category            setEventCategory() Sets the current record's "EventCategory" collection
 * 
 * @package    trevents
 * @subpackage model
 * @author     Ville Riikonen § huqa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EventCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}