<?php

/**
 * OrganizerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organizer');
    }
}